{{- if and .Values.rbac.create .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sealos-storage-manager.backendServiceAccountName" . | quote }}
  namespace: {{ include "sealos-storage-manager.namespace" . | quote }}
  labels:
    {{- include "sealos-storage-manager.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "sealos-storage-manager.backendClusterRoleName" . | quote }}
  labels:
    {{- include "sealos-storage-manager.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "pods", "pods/log", "events"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectaccessreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "sealos-storage-manager.backendClusterRoleName" . | quote }}
  labels:
    {{- include "sealos-storage-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "sealos-storage-manager.backendClusterRoleName" . | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sealos-storage-manager.backendServiceAccountName" . | quote }}
    namespace: {{ include "sealos-storage-manager.namespace" . | quote }}
{{- end }}
