apiVersion: v1
kind: Service
metadata:
  name: viewer-web
  namespace: sealos-storage-manager
spec:
  selector:
    app.kubernetes.io/name: viewer-web
  ports:
    - name: http
      port: 80
      targetPort: http
