apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backend.service.name | quote }}
  namespace: {{ include "storage-manager.namespace" . | quote }}
  labels:
    {{- include "storage-manager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "storage-manager.backendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/backend-configmap.yaml") . | sha256sum }}
      labels:
        {{- include "storage-manager.backendSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "storage-manager.backendServiceAccountName" . | quote }}
      containers:
        - name: backend
          image: {{ include "storage-manager.backendImage" . | quote }}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy | quote }}
          env:
            - name: CONFIG
              value: {{ printf "%s/viewer.yaml" .Values.backend.configMountPath | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.containerPort }}
          volumeMounts:
            - name: config
              mountPath: {{ .Values.backend.configMountPath | quote }}
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ .Values.backend.configMapName | quote }}
