{{- if .Values.web.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.web.service.name | quote }}
  namespace: {{ include "storage-manager.namespace" . | quote }}
  labels:
    {{- include "storage-manager.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.web.ingress.className | quote }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    {{- with .Values.web.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.web.ingress.className }}
  ingressClassName: {{ .Values.web.ingress.className | quote }}
  {{- end }}
  rules:
    - host: {{ include "storage-manager.webHost" . | quote }}
      http:
        paths:
          - path: {{ .Values.web.ingress.path | quote }}
            pathType: {{ .Values.web.ingress.pathType | quote }}
            backend:
              service:
                name: {{ .Values.web.service.name | quote }}
                port:
                  number: {{ .Values.web.service.port }}
  {{- if and .Values.web.ingress.tls.enabled (not (eq (toString (default false .Values.disableHttps)) "true")) }}
  tls:
    - hosts:
        - {{ include "storage-manager.webHost" . | quote }}
      secretName: {{ default (default "wildcard-cert" .Values.certSecretName) .Values.web.ingress.tls.secretName | quote }}
  {{- end }}
{{- end }}
