ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - .
  - packages/*
patchedDependencies:
  container-query-polyfill@1.0.2: patches/container-query-polyfill@1.0.2.patch

onlyBuiltDependencies:
  - core-js
